  - name: Load OS-specific vars
    include_vars: "{{ lookup('first_found', params) }}"
    vars:
      params:
        files:
          - '{{ansible_distribution}}.yml'
          - '{{ansible_os_family}}.yml'
          - main.yml
        paths:
          - 'vars'

  - include_tasks: Archlinux.yml
    when: ansible_os_family == 'Archlinux'
  
  - name: Update lynis
    tags:
    - update
    - lynis
    become: true
    become_method: doas
    ansible.builtin.shell: lynis update info
