---
- name: Load OS-specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
        - main.yml
      paths:
        - 'vars'

- ansible.builtin.include_tasks: Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Start cups service
  tags:
  - start
  - cups
  become: true
  become_method: doas
  ansible.builtin.service:
    name: cups
    state: started
    enabled: true

- ansible.builtin.include_tasks: cups-server.yml
  when: ( 'cups-server' in inventory_file )
