services:
  <name>: 
    image: <path>:latest
    container_name: <name>
    devices:
      - <external_device_path>:<internal_device_path>
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - <external_path>:<inernal_path>
    ports:
      - <external_port>:<internal_port>/<tcp/udp>
    deploy:
      resources:
        limits:
          memory: <#M/G>
    restart: unless-stopped
    
