---
- name: Build Arch Server
  hosts: server
  tasks:
  - name: install programs via pacman
    pacman:
      name:
        - btop
        - docker
        - docker-compose
        - flatpak
        - opendoas
        - ranger
        - tmux
      state: present

  - name: create group for ssh users
    group:
      name: sshusers

  - name: create new user with password, add to groups
      user:
        name: nick
        password: "{{ user_pw | password_hash('sha512')}}"
        groups: sshusers
        shell: /bin/bash

  - name: limit doas to nick
    lineinfile:
      path: /etc/doas.conf
      line: permit persist nick
    
  - name: add authorized keys for new user
    authorized_key:
      user: nick
      key: "/home/nick/.ssh/id_ed25519.pub"

  - name: update and upgrade
    become: true
    pacman:
      update_cache: yes
      upgrade: yes

  - name: secure ssh configuration 
    become: true
    blockinfile:
      path: /etc/ssh/sshd_config
      block: |
        ########################################################################################################
        # start settings from https://infosec.mozilla.org/guidelines/openssh#modern-openssh-67 as of 2019-01-01
        ########################################################################################################
        # Supported HostKey algorithms by order of preference.
        HostKey /etc/ssh/ssh_host_ed25519_key
        KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
        Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
        MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
        # LogLevel VERBOSE logs user's key fingerprint on login. Needed to have a clear audit track of which key was using to log in.
        LogLevel VERBOSE
        # Use kernel sandbox mechanisms where possible in unprivileged processes
        # Systrace on OpenBSD, Seccomp on Linux, seatbelt on MacOSX/Darwin, rlimit elsewhere.
        # Note: This setting is deprecated in OpenSSH 7.5 (https://www.openssh.com/txt/release-7.5)
        # UsePrivilegeSeparation sandbox
        ########################################################################################################
        # end settings from https://infosec.mozilla.org/guidelines/openssh#modern-openssh-67 as of 2019-01-01
        ########################################################################################################
        # don't let users set environment variables
        PermitUserEnvironment no
        # only use the newer, more secure protocol
        Protocol 2
        # disable port forwarding
        AllowTcpForwarding no
        AllowStreamLocalForwarding no
        GatewayPorts no
        PermitTunnel no
        # don't allow login if the account has an empty password
        PermitEmptyPasswords no
        # ignore .rhosts and .shosts
        IgnoreRhosts yes
        # verify hostname matches IP
        UseDNS yes
        Compression no
        TCPKeepAlive no
        AllowAgentForwarding no
        # don't allow .rhosts or /etc/hosts.equiv
        HostbasedAuthentication no
      notify: restart ssh service

    - name: secure ssh configuration part 2
      become: true
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^AllowGroups', line: 'AllowGroups sshusers' }
        - { regexp: '^ClientAliveCountMax', line: 'ClientAliveCountMax 0'}
        - { regexp: '^ClientAliveInterval', line: 'ClientAliveInterval 300'}
        - { regexp: '^ListenAddress', line: 'ListenAddress 0.0.0.0'}
        - { regexp: '^LoginGraceTime', line: 'LoginGraceTime 30'}
        - { regexp: '^MaxAuthTries', line: 'MaxAuthTries 2'}
        - { regexp: '^MaxSessions', line: 'MaxSessions 2'}
        - { regexp: '^MaxStartups', line: 'MaxStartups 2'}
        - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no'}
        - { regexp: '^Port', line: 'Port 22'}
        - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no'}
        - { regexp: '^X11Forwarding', line: 'X11Forwarding no'}
        - { regexp: '^Subsystem', line: 'Subsystem sftp  internal-sftp -f AUTHPRIV -l INFO'}
      notify: restart ssh service

    - name: remove short diffie diffie-hellman
      become: true
      shell: |
        awk '$5 >= 3071' /etc/ssh/moduli | sudo tee /etc/ssh/moduli.tmp
        mv /etc/ssh/moduli.tmp /etc/ssh/moduli
      notify: restart ssh service

    - name: remove default auditd rules and download best practice rules
      become: true
      shell: |
        rm /etc/audit/rules.d/audit.rules
        wget -P /etc/audit/rules.d/ https://raw.githubusercontent.com/Neo23x0/auditd/master/audit.rules
        service auditd restart
