all:
  children:
    server:
      hosts:
        ginko:
          ansible_host: 10.10.10.7
        insatsu:
          ansible_host: 10.10.10.8
        tako:
          ansible_host: 10.10.10.9
        takara:
          ansible_host: 10.10.10.10
    client:
      hosts:
        tomoe:
          ansible_host: 10.10.10.12
        daruma:
          ansible_host: 10.10.10.14
        tachigami:
          ansible_host: 10.10.10.15
    firewall:
      hosts:
        kabe:
          ansible_host: 10.10.10.1
