all:
  children:
    archserver:
      hosts:
        ginko:
          ansible_host: 10.10.10.7
        takara:
          ansible_host: 10.10.10.10
    archclient:
      hosts:
        tomoe:
          ansible_host: 10.10.10.12
        tachigami:
          ansible_host: 10.10.10.15
    ubuntuserver:
      hosts:
        insatsu:
          ansible_host: 10.10.10.8
    ubuntuclient:
      hosts:
        daruma:
          ansible_host: 10.10.10.14
    debianserver:
      hosts:
        tako:
          ansible_host: 10.10.10.9
    pfsense:
      hosts:
        kabe:
          ansible_host: 10.10.10.1
