all:
  children:
    client:
      hosts:
        name:
          ansible_host: x.x.x.x
    server:
      hosts:
        name:
          ansible_host: x.x.x.x
    cups-server:
      hosts:
        name:
          ansible_host: x.x.x.x
