all:
  children:
    server:
      hosts:
        name:                   #Change me
          ansible_host: x.x.x.x #Change me
        name:                   #Change me
          ansible_host: x.x.x.x #Change me
    client:
      hosts:
        name:                   #Change me
          ansible_host: x.x.x.x #Change me
        name:                   #Change me
          ansible_host: x.x.x.x #Change me
