services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    volumes:
      - /srv/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    <<: *env
    deploy:
      resources:
        limits:
          memory: 1G