services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    ports: 
      - 8123:8123
    volumes:
      - /srv/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    <<: *env
    privileged: true
    deploy:
      resources:
        limits:
          memory: 1G