services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - /srv/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    restart: unless-stopped
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    deploy:
      resources:
        limits:
          memory: 100M

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 8080:80
    volumes:
      - /srv/nextcloud:/var/www/html
      - /mnt/storage:/mnt/storage
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    restart: unless-stopped
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user
    deploy:
      resources:
        limits:
          memory: 500M

volumes:
  nextcloud:
  db:

secrets:
  nextcloud_admin_user:
    file: ./nextcloud_admin_user.txt
  nextcloud_admin_password:
    file: ./nextcloud_admin_password.txt
  postgres_password:
    file: ./postgres_password.txt
  postgres_db:
    file: ./postgres_db.txt
  postgres_user:
    file: ./postgres_user.txt
