services:
  octoprint:
    image: octoprint/octoprint
    ports:
      - 80:80
    devices:
    # use `python -m serial.tools.miniterm` to see what the name is of the printer, this requires pyserial
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video0:/dev/video0
    volumes:
     - /srv/octoprint:/octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    restart: unless-stopped
  
  ####
  # uncomment if you wish to edit the configuration files of octoprint
  # refer to docs on configuration editing for more information
  ####

  #config-editor:
  #  image: linuxserver/code-server
  #  ports:
  #    - 8443:8443
  #  depends_on:
  #    - octoprint
  #  restart: unless-stopped
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=America/Chicago
  #  restart: unless-stopped
  #  volumes:
  #    - octoprint:/octoprint

volumes:
  octoprint: