services:
  papermc:
    image: marctv/minecraft-papermc-server:latest
    container_name: papermc
    ports:
      - 25565:25565
    volumes:
      - /srv/papermc/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 9.5G