services:
  papermc:
    image: marctv/minecraft-papermc-server:latest
    container_name: papermc
    ports:
      - 25565:25565
    volumes:
      - /srv/papermc/data:/data
    <<: *env
    deploy:
      resources:
        limits:
          memory: 9.5G