services:
  shinobi:
    image: registry.gitlab.com/shinobi-systems/shinobi:dev
    container_name: shinobi
    ports:
      - 8081:8080/tcp
    volumes:
      - /dev/shm/Shinobi/streams/:/dev/shm/streams:rw
      - /srv/shinobi/config/:/config:rw
      - /srv/shinobi/customAutoLoad/:/home/Shinobi/libs/customAutoLoad:rw
      - /srv/shinobi/database/:/var/lib/mysql:rw
      - /srv/shinobi/videos/:/home/Shinobi/videos:rw
      - /srv/shinobi/plugins/:/home/Shinobi/plugins:rw
    <<: *env
    deploy:
      resources:
        limits:
          memory: 4G