services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    ports:
      - 80:80
    volumes:
      - /srv/vw-data:/data
    <<: *env
    deploy:
      resources:
        limits:
          memory: 500M