services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    ports:
      - 81:80
    volumes:
      - /srv/vw-data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M