  - name: Install cups via pacman
    tags:
    - init
    - cups
    become: true
    become_method: doas
    community.general.pacman:
      name:
        - cups
      state: present
    notify: Restart cups
