  - name: Update and upgrade
    tags:
    - update
    become: true
    become_method: doas
    community.general.apt:
      update_cache: true
      upgrade: true
      autoremove: true
      autoclean: true
