  - name: Load OS-specific vars
    include_vars: "{{ lookup('first_found', params) }}"
    vars:
      params:
        files:
          - '{{ansible_distribution}}.yml'
          - '{{ansible_os_family}}.yml'
          - main.yml
  
  - include_tasks: Archlinux.yml
    when: ansible_os_family == 'Archlinux'

  - name: Install kids flatpaks
    community.general.flatpak:
      name:  
        - edu.mit.Scratch
        - net.sourceforge.ExtremeTuxRacer
        - net.supertuxkart.SuperTuxKart
        - org.kde.gcompris
        - org.kde.knights
        - org.kde.kolourpaint
        - org.neverball.Neverball
        - org.supertuxproject.SuperTux
        - party.supertux.supertuxparty
      state: present