-name: Arch flatpak install and config
  hosts: archclient
  tasks:
  - name: Install flatpak via pacman
    tags:
    - packages
    become: true
    become_method: doas
    community.general.pacman:
      name:
        - flatpak
      state: present

# Go to roles/flatpak/tasks/main.yml

  - name: Uninstall packages from pacman
    community.general.pacman:
      name:
        - ark
        - firefox
        - chromium
        - gwenview
        - kcalc
        - kwrite
        - obsidian
        - okular
        - vlc
      state: absent
