  - name: Load OS-specific vars
    include_vars: "{{ lookup('first_found', params) }}"
    vars:
      params:
        files:
          - '{{ansible_distribution}}.yml'
          - '{{ansible_os_family}}.yml'
          - main.yml

  - include_tasks: Archlinux.yml
    when: ansible_os_family == 'Archlinux'

  - name: Add the flathub flatpak repository remote to the user installation
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: user

  - name: Install standard flatpaks
    community.general.flatpak:
      name:  
        - ark
        - firefox
        - chromium
        - flatseal
        - gwenview
        - kcalc
        - kwrite
        - md.obsidian.Obsidian
        - okular
        - vlc
      state: present
