  - name: Add the flathub flatpak repository remote to the user installation
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: user

  - name: Install standard flatpaks
    community.general.flatpak:
      name:  
        - ark
        - firefox
        - chromium
        - flatseal
        - gwenview
        - kcalc
        - kwrite
        - md.obsidian.Obsidian
        - okular
        - vlc
      state: present