  - name: Install tailscale via pacman
    tags:
    - init
    - packages
    become: true
    community.general.pacman:
      name:
        - tailscale
      state: present

  - name: Tailscale service setup
    - init
    - tailscale
    become: true
    become_method: doas
    ansible.builtin.service:
      name: tailscaled
      state: started
      enabled: true