  - name: Tailscale service setup
    tags:
    - init
    - tailscale
    become: true
    become_method: doas
    ansible.builtin.service:
      name: tailscaled
      state: started
      enabled: true
