  - name: Load OS-specific vars
    include_vars: "{{ lookup('first_found', params) }}"
    vars:
      params:
        files:
          - '{{ansible_distribution}}.yml'
          - '{{ansible_os_family}}.yml'
          - main.yml

  - include_tasks: Archlinux.yml
    when: ansible_os_family == 'Archlinux'
  
  - name: Tailscale service setup
    tags:
    - init
    - tailscale
    become: true
    become_method: doas
    ansible.builtin.service:
      name: tailscaled
      state: started
      enabled: true
