-name: Arch git install and config
  hosts: arch
  tasks:
  - name: Install git via pacman
    tags:
    - packages
    become: true
    become_method: doas
    community.general.pacman:
      name:
        - git
      state: present
