-name: Arch git install and config
  hosts: arch
  tasks:
  - name: Install git via pacman
    tags:
    - packages
    become: true
    become_method: doas
    community.general.pacman:
      name:
        - git
      state: present

  - name: Configure git global username
    git_config:
      name: user.name
      scope: global
      value: "Nick Eigel"

  - name: Configure git global email
    git_config:
      name: user.email
      scope: global
      value: "nickeigel@gmail.com"

  - name: Configure git global editor
    git_config:
      name: core.editor 
      scope: global
      value: "nano -w"
