  - name: Install docker via pacman
    tags:
    - init
    - docker
    become: true
    become_method: doas
    community.general.pacman:
      name:
        - docker
        - docker-compose
      state: present
