---
- name: Add cups docker-compose file
  tags: 
  - server
  - docker
  - cups
  ansible.builtin.copy:
    src: ./config/docker/cups.yml
    dest: ~/docker/cups.yml
    force: true

- name: Start cups docker-compose
  tags:
  - server
  - docker
  - cups
  ansible.builtin.shell: docker-compose -f docker/cups.yml up -d
  
